### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by sjlagasse** [lythro10/Tea-Cozy-Georgios-Michael#4]
Overall, you did a good job on your project. Your HTML was on point. Nice job using wrapping divs. Both files used all of the right elements and styles. Your CSS was nice and you built the page correctly. Great job with getting your nav to work. Lastly, nice job keeping both of your files properly indented. All in all, nice job with your project and good job following the spec.

**Comment by lythro10** [comment]
Thank you for your feedback !!!
